### ISSUE TITLE
H5000 WebSocket Documentation

### ISSUE THREAD

**Issue by spencerogden** [LoonSongSoftware/B-G-H5000-Logger#3]
In your Sailing Anarchy post you mentioned B&G Documentation about the Web Socket API. Is this available somewhere? Specifically info about send data and settings to H5000.

**Comment by LoonSongSoftware** [comment]
I’m about to start an offshore race (BERMUDA ONE-TWO). I’ll post the document/link when I’m back home (probably next Wednesday).

On Jun 15, 2023, at 8:14 AM, Spencer Ogden ***@***.***> wrote:

﻿

In your Sailing Anarchy post you mentioned B&G Documentation about the Web Socket API. Is this available somewhere? Specifically info about send data and settings to H5000.

**Comment by spencerogden** [comment]
Fantastic. Which boat? I'm up in Newport.

**Comment by LoonSongSoftware** [comment]
Resolute. Just finished (after rudder bearing failed) and am heading back to Maine.

On Jun 15, 2023, at 11:47 AM, Spencer Ogden ***@***.***> wrote:

﻿

Fantastic. Which boat? I'm up in Newport.

**Comment by spencerogden** [comment]
Hi,

I hope you had a great race. Any chance you have the web sockets
documentation that covers settings?


Spencer
203-559-9145

**Comment by LoonSongSoftware** [comment]
Sorry for the delay…I’ve been focused on boat repairs—several and expensive!—and on catching up on other business since I’ve been away for the better part of a month.

Anyway, here are two B&G documents about the websocket interface.  For the logger, I relied mostly (entirely?) on the “WebSocket” document.

(We’ll see how attachments work with GitHub messages.  If it doesn’t work, I’ll add the files to the repository.)

**Comment by spencerogden** [comment]
No attachments come through. No rush, thanks for your follow up.

**Comment by LoonSongSoftware** [comment]
I added the documents to the “resources” folder of the repository on GitHub.

**Comment by spencerogden** [comment]
Thanks very much!
